catsapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

end

catsapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

catsapp/app/models/cat.rb
require 'date'

class Cat < ApplicationRecord
  validates :birth_date, presence: true
  validates :color, presence: true
  validates :name, presence:true
  validates :description, presence: true
  validates :sex, presence: true, inclusion: {in: ['F', 'M']}

  def age
    now = Date.today
    days = now - self[:birth_date]
    years = days / 365 
    years.to_i
  end
end

catsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

catsapp/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    # debugger
    @cat = Cat.new(cat_params)

    if @cat.save
      # debugger
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
 
    @cat = Cat.find(params[:id])
    render :edit   
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      redirect_to edit_cat_url
    end

  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

catsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

catsapp/app/helpers/cats_helper.rb
module CatsHelper
end

catsapp/app/views/cats/_form.html.erb
<% if type == :new %>
  <% action_url = cats_url %>
  <% button_text = 'Create Cat' %>
<% elsif type == :edit %>
  <% action_url = cat_url(cat) %>
  <% button_text = 'Update Cat' %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="name">Name:
    <input type="text" id="name" name="cat[name]" value="<%= @cat.name %>">
  </label>
  <label for="birth_date">birth_date:
    <input type="date" id="birth_date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  </label>
  <label for="color">color:</label>
  <select name='cat[color]' id="color">
    <option value="black" <%= @cat.color == "black" ? "selected" : "" %> >black</option>
    <option value="white" <%= @cat.color == "white" ? "selected" : "" %>>white</option>
    <option value="orange" <%= @cat.color == "orange" ? "selected" : "" %>>orange</option>
    <option value="green" <%= @cat.color == "green" ? "selected" : "" %>>green</option>
    <option value="calico" <%= @cat.color == "calico" ? "selected" : "" %>>calico</option>
  </select>
  <br>
  <label for="sex">Sex</label>
  <input type="radio" name="cat[sex]" value="M" id="male" <%= @cat.sex == "M" ? "checked" : "" %>>
  <label for="male">Male</label>
  <input type="radio" name="cat[sex]" value="F" id="female" <%= @cat.sex == "F" ? "checked" : "" %>>
  <label for="female">Female</label>
  <br>
  <label for="description">Description:</label>
  <br>
  <textarea name="cat[description]" id="description"><%=@cat.description%></textarea>
  <br>
  <input type="submit" value="<%= button_text %>%">
</form>

catsapp/app/views/cats/edit.html.erb
<% render 'form', cat_var: @cat, action: :edit %>

catsapp/app/views/cats/index.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2">All the Cats!</th>
        </tr>
    </thead>
    <tbody>
      <% @cats.each do |cat| %>
        <tr>
            <td><%= cat.name %></td>
            <td><a href="<%= cat_url(cat)%>">Page</a></td>
        </tr>
      <% end %>
    </tbody>
</table>

catsapp/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
  <label for="name">Name:
    <input type="text" id="name" name="cat[name]" value:"<%=@cat.name%>">
  </label>
  <label for="birth_date">birth_date:
    <input type="date" id="birth_date" name="cat[birth_date]" value:"<%=@cat.birth_date%>"
  </label>
  <label for="color">color:</label>
  <select name='cat[color]' id="color">
    <option value="black">black</option>
    <option value="white">white</option>
    <option value="orange">orange</option>
    <option value="green">green</option>
    <option value="calico">calico</option>
    <option disabled selected>Choose A Color</option>
  </select>
  <br>
  <label for="sex">Sex</label>
  <input type="radio" name="cat[sex]" value="M" id="male">
  <label for="male">Male</label>
  <input type="radio" name="cat[sex]" value="F" id="female">
  <label for="female">Female</label>
  <br>
  <label for="description">Description:</label>
  <br>
  <textarea name="cat[description]" id="description"></textarea>
  <br>
  <input type="submit" value="Create Cat!">
</form>

catsapp/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%=@cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Age</td>
            <td><%=@cat.age%></td>
        </tr>
        <tr>
            <td>Birth_Date</td>
            <td><%=@cat.birth_date%></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%=@cat.color%></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%=@cat.sex%></td>
        </tr>
        
    </tbody>
</table>

catsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>